// Data: Smartphones
const products = [
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        brand: "Apple",
        price: 280000,
        image: "Photos/Iphone 15 pro max.jpg",
        rating: 5.0,
        specs: {
            screen: "6.7\" Super Retina XDR OLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "48MP Main + 12MP Front",
            battery: "4422mAh / 27W",
            processor: "A17 Pro Bionic",
            network: "5G Support",
        },
        tags: ["New"],
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        brand: "Samsung",
        price: 320000,
        image: "Photos/Samsung_galaxy_s25_ultra_1.jpg",
        rating: 5.0,
        specs: {
            screen: "6.8\" Dynamic AMOLED 2X",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "200MP Quad + 12MP Front",
            battery: "5000mAh / 45W",
            processor: "Snapdragon 8 Gen 3",
            network: "5G Support",
        },
        tags: ["AI Features"],
    },
    {
        id: 3,
        name: "Xiaomi 14 Ultra",
        brand: "Xiaomi",
        price: 245000,
        image: "Photos/Xiaomi_14_Ultra.jpg",
        rating: 4.8,
        specs: {
            screen: "6.73\" LTPO AMOLED",
            refresh: "120Hz",
            ram: "16GB",
            storage: "512GB",
            camera: "50MP Quad Leica + 32MP Front",
            battery: "5000mAh / 90W",
            processor: "Snapdragon 8 Gen 3",
            network: "5G Support",
        },
        tags: ["Leica Camera"],
    },
    {
        id: 4,
        name: "Oppo Reno 11 Pro",
        brand: "Oppo",
        price: 115000,
        image: "Photos/Oppo_Reno_11_Pro.jpg",
        rating: 4.5,
        specs: {
            screen: "6.7\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "256GB",
            camera: "50MP Triple + 32MP Front",
            battery: "4600mAh / 80W",
            processor: "Dimensity 8200",
            network: "5G Support",
        },
    },
    {
        id: 5,
        name: "Google Pixel 8 Pro",
        brand: "Google Pixel",
        price: 195000,
        image: "Photos/Google_Pixel_8_Pro.jpg",
        rating: 4.7,
        specs: {
            screen: "6.7\" LTPO OLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "128GB",
            camera: "50MP Triple + 10.5MP Front",
            battery: "5050mAh / 30W",
            processor: "Google Tensor G3",
            network: "5G Support",
        },
    },
    {
        id: 6,
        name: "Realme 12 Pro+",
        brand: "Realme",
        price: 98000,
        image: "Photos/Realme_12_Pro+.jpg",
        rating: 4.4,
        specs: {
            screen: "6.7\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP + 64MP Periscope",
            battery: "5000mAh / 67W",
            processor: "Snapdragon 7s Gen 2",
            network: "5G Support",
        },
    },
    {
        id: 7,
        name: "Samsung Galaxy A55",
        brand: "Samsung",
        price: 82000,
        image: "Photos/Samsung_Galaxy_A55.jpg",
        rating: 4.6,
        specs: {
            screen: "6.6\" Super AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP Triple + 32MP Front",
            battery: "5000mAh / 25W",
            processor: "Exynos 1480",
            network: "5G Support",
        },
    },
    {
        id: 8,
        name: "Nothing Phone (2)",
        brand: "Nothing",
        price: 135000,
        image: "Photos/Nothing_Phone_(2).jpg",
        rating: 4.8,
        specs: {
            screen: "6.7\" LTPO OLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "256GB",
            camera: "50MP Dual + 32MP Front",
            battery: "4700mAh / 45W",
            processor: "Snapdragon 8+ Gen 1",
            network: "5G Support",
        },
        tags: ["Unique Design"],
    },
    {
        id: 9,
        name: "Huawei P60 Pro",
        brand: "Huawei",
        price: 210000,
        image: "Photos/Huawei_P60_Pro.jpg",
        rating: 4.7,
        specs: {
            screen: "6.67\" LTPO OLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "48MP Triple XMAGE",
            battery: "4815mAh / 88W",
            processor: "Snapdragon 8+ Gen 1",
            network: "4G Support",
        },
        tags: ["Makash f algeria"],
    },
    {
        id: 10,
        name: "Redmi Note 13 Pro+",
        brand: "Xiaomi",
        price: 88000,
        image: "Photos/Redmi_Note_13_Pro+.jpg",
        rating: 4.5,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "200MP Triple + 16MP Front",
            battery: "5000mAh / 120W",
            processor: "Dimensity 7200 Ultra",
            network: "5G Support",
        },
    },
    {
        id: 11,
        name: "OnePlus 12",
        brand: "OnePlus",
        price: 225000,
        image: "Photos/OnePlus_12.jpg",
        rating: 4.9,
        specs: {
            screen: "6.82\" LTPO4 AMOLED",
            refresh: "120Hz",
            ram: "16GB",
            storage: "512GB",
            camera: "50MP Hasselblad + 32MP Front",
            battery: "5400mAh / 100W",
            processor: "Snapdragon 8 Gen 3",
            network: "5G Support",
        },
    },
    {
        id: 12,
        name: "Vivo V30 Pro",
        brand: "Vivo",
        price: 145000,
        image: "Photos/Vivo_V30_Pro.jpg",
        rating: 4.6,
        specs: {
            screen: "6.78\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP Triple ZEISS + 50MP Front",
            battery: "5000mAh / 80W",
            processor: "Dimensity 8200",
            network: "5G Support",
        },
    },
    {
        id: 13,
        name: "Oppo Reno 12 Pro",
        brand: "Oppo",
        price: 125000,
        image: "Photos/Oppo_Reno_12_Pro.jpg",
        rating: 4.7,
        specs: {
            screen: "6.7\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP Triple + 50MP Front",
            battery: "5000mAh / 80W",
            processor: "Dimensity 7300-Energy",
            network: "5G Support",
        },
    },
    {
        id: 14,
        name: "Samsung Galaxy A35",
        brand: "Samsung",
        price: 68000,
        image: "Photos/Samsung_galaxy_a15/Samsung_galaxy_a15_1.jpg",
        rating: 4.3,
        specs: {
            screen: "6.6\" Super AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "128GB",
            camera: "50MP Triple + 13MP Front",
            battery: "5000mAh / 25W",
            processor: "Exynos 1380",
            network: "5G Support",
        },
        tags: ["Just a test "],
    },
    {
        id: 15,
        name: "Redmi Note 13",
        brand: "Xiaomi",
        price: 45000,
        image: "Photos/Redmi_Note_13.jpg",
        rating: 4.2,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "108MP Triple + 16MP Front",
            battery: "5000mAh / 33W",
            processor: "Snapdragon 685",
            network: "4G Support",
        },
    },

    {
        id: 16,
        name: "Samsung Galaxy A05s",
        brand: "Samsung",
        price: 23500,
        image: "Photos/Samsung_Galaxy_A05s.jpg",
        rating: 4.2,
        specs: {
            screen: "6.7\" PLS LCD",
            refresh: "90Hz",
            ram: "4GB",
            storage: "128GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Snapdragon 680",
            network: "4G",
        },
    },
    {
        id: 17,
        name: "Xiaomi Redmi 13C",
        brand: "Xiaomi",
        price: 26000,
        image: "Photos/Xiaomi_Redmi_13C.jpg",
        rating: 4.1,
        specs: {
            screen: "6.74\" IPS LCD",
            refresh: "90Hz",
            ram: "6GB",
            storage: "128GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Helio G85",
            network: "4G",
        },
    },
    {
        id: 18,
        name: "Realme C53",
        brand: "Realme",
        price: 25000,
        image: "Photos/Realme_C53.jpg",
        rating: 4.0,
        specs: {
            screen: "6.74\" IPS LCD",
            refresh: "90Hz",
            ram: "6GB",
            storage: "128GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Unisoc T612",
            network: "4G",
        },
    },
    {
        id: 19,
        name: "Infinix Hot 40i",
        brand: "Infinix",
        price: 22000,
        image: "Photos/Infinix_Hot_40i.jpg",
        rating: 4.0,
        specs: {
            screen: "6.56\" IPS LCD",
            refresh: "90Hz",
            ram: "4GB",
            storage: "128GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Unisoc T606",
            network: "4G",
        },
    },
    {
        id: 20,
        name: "Tecno Spark 20",
        brand: "Tecno",
        price: 24500,
        image: "Photos/Tecno_Spark_20.jpg",
        rating: 4.1,
        specs: {
            screen: "6.6\" IPS LCD",
            refresh: "90Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Helio G85",
            network: "4G",
        },
    },
    {
        id: 21,
        name: "Samsung Galaxy A15",
        brand: "Samsung",
        price: 34000,
        image: "Photos/Samsung_Galaxy_A15.jpg",
        rating: 4.5,
        specs: {
            screen: "6.5\" Super AMOLED",
            refresh: "90Hz",
            ram: "6GB",
            storage: "128GB",
            camera: "50MP Main",
            battery: "5000mAh",
            processor: "Helio G99",
            network: "4G",
        },
    },
    {
        id: 22,
        name: "Xiaomi Redmi A3",
        brand: "Xiaomi",
        price: 18500,
        image: "Photos/Xiaomi_Redmi_A3.jpg",
        rating: 3.8,
        specs: {
            screen: "6.71\" IPS LCD",
            refresh: "90Hz",
            ram: "3GB",
            storage: "64GB",
            camera: "8MP Main",
            battery: "5000mAh",
            processor: "Helio G36",
            network: "4G",
        },
    },
    {
        id: 23,
        name: "Samsung Galaxy A25",
        brand: "Samsung",
        price: 46000,
        image: "Photos/Samsung_Galaxy_A25.jpg",
        rating: 4.6,
        specs: {
            screen: "6.5\" Super AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP OIS",
            battery: "5000mAh",
            processor: "Exynos 1280",
            network: "5G",
        },
    },
    {
        id: 24,
        name: "Xiaomi Redmi Note 13 Pro 4G",
        brand: "Xiaomi",
        price: 54000,
        image: "Photos/Xiaomi_Redmi_Note_13_Pro_4G.jpg",
        rating: 4.7,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "200MP OIS",
            battery: "5000mAh",
            processor: "Helio G99 Ultra",
            network: "4G",
        },
    },
    {
        id: 25,
        name: "Realme 11 Pro",
        brand: "Realme",
        price: 62000,
        image: "Photos/Realme_11_Pro.jpg",
        rating: 4.6,
        specs: {
            screen: "6.7\" AMOLED Curved",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "100MP OIS",
            battery: "5000mAh",
            processor: "Dimensity 7050",
            network: "5G",
        },
    },
    {
        id: 26,
        name: "Infinix Note 40 Pro",
        brand: "Infinix",
        price: 58000,
        image: "Photos/Infinix_Note_40_Pro.jpg",
        rating: 4.5,
        specs: {
            screen: "6.78\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "256GB",
            camera: "108MP OIS",
            battery: "5000mAh",
            processor: "Helio G99 Ultimate",
            network: "4G",
        },
    },
    {
        id: 27,
        name: "Poco X6 Pro",
        brand: "Xiaomi",
        price: 78000,
        image: "Photos/Poco_X6_Pro.jpg",
        rating: 4.8,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "64MP OIS",
            battery: "5000mAh",
            processor: "Dimensity 8300 Ultra",
            network: "5G",
        },
    },
    {
        id: 28,
        name: "Samsung Galaxy M55",
        brand: "Samsung",
        price: 69000,
        image: "Photos/Samsung_Galaxy_M55.jpg",
        rating: 4.4,
        specs: {
            screen: "6.7\" Super AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP OIS",
            battery: "5000mAh",
            processor: "Snapdragon 7 Gen 1",
            network: "5G",
        },
    },
    {
        id: 29,
        name: "Oppo Reno 11 F",
        brand: "Oppo",
        price: 65000,
        image: "Photos/Oppo_Reno_11_F.jpg",
        rating: 4.5,
        specs: {
            screen: "6.7\" AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "64MP Main",
            battery: "5000mAh",
            processor: "Dimensity 7050",
            network: "5G",
        },
    },
    {
        id: 30,
        name: "Tecno Camon 30",
        brand: "Tecno",
        price: 49000,
        image: "Photos/Tecno_Camon_30.jpg",
        rating: 4.3,
        specs: {
            screen: "6.78\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP OIS",
            battery: "5000mAh",
            processor: "Helio G99 Ultimate",
            network: "4G",
        },
    },
    {
        id: 31,
        name: "Samsung Galaxy S23 FE",
        brand: "Samsung",
        price: 95000,
        image: "Photos/Samsung_Galaxy_S23_FE.jpg",
        rating: 4.6,
        specs: {
            screen: "6.4\" Dynamic AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP Triple",
            battery: "4500mAh",
            processor: "Exynos 2200",
            network: "5G",
        },
    },
    {
        id: 32,
        name: "Xiaomi 13T",
        brand: "Xiaomi",
        price: 89000,
        image: "Photos/Xiaomi_13T.jpg",
        rating: 4.7,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "144Hz",
            ram: "12GB",
            storage: "256GB",
            camera: "50MP Leica",
            battery: "5000mAh",
            processor: "Dimensity 8200 Ultra",
            network: "5G",
        },
    },
    {
        id: 33,
        name: "Poco F6",
        brand: "Xiaomi",
        price: 92000,
        image: "Photos/Poco_F6.jpg",
        rating: 4.8,
        specs: {
            screen: "6.67\" AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP OIS",
            battery: "5000mAh",
            processor: "Snapdragon 8s Gen 3",
            network: "5G",
        },
    },
    {
        id: 34,
        name: "Google Pixel 7a",
        brand: "Google Pixel",
        price: 85000,
        image: "Photos/Google_Pixel_7a.jpg",
        rating: 4.5,
        specs: {
            screen: "6.1\" OLED",
            refresh: "90Hz",
            ram: "8GB",
            storage: "128GB",
            camera: "64MP Dual",
            battery: "4385mAh",
            processor: "Tensor G2",
            network: "5G",
        },
    },
    {
        id: 35,
        name: "Realme GT 6",
        brand: "Realme",
        price: 115000,
        image: "Photos/Realme_GT_6.jpg",
        rating: 4.9,
        specs: {
            screen: "6.78\" LTPO AMOLED",
            refresh: "120Hz",
            ram: "16GB",
            storage: "512GB",
            camera: "50MP OIS",
            battery: "5500mAh",
            processor: "Snapdragon 8s Gen 3",
            network: "5G",
        },
    },
    {
        id: 36,
        name: "OnePlus 12R",
        brand: "OnePlus",
        price: 120000,
        image: "Photos/OnePlus_12R.jpg",
        rating: 4.7,
        specs: {
            screen: "6.78\" LTPO4 AMOLED",
            refresh: "120Hz",
            ram: "16GB",
            storage: "256GB",
            camera: "50MP OIS",
            battery: "5500mAh",
            processor: "Snapdragon 8 Gen 2",
            network: "5G",
        },
    },
    {
        id: 37,
        name: "Samsung Galaxy S24",
        brand: "Samsung",
        price: 165000,
        image: "Photos/Samsung_Galaxy_S24.jpg",
        rating: 4.8,
        specs: {
            screen: "6.2\" Dynamic LTPO",
            refresh: "120Hz",
            ram: "8GB",
            storage: "256GB",
            camera: "50MP Triple",
            battery: "4000mAh",
            processor: "Exynos 2400",
            network: "5G",
        },
    },
    {
        id: 38,
        name: "iPhone 13",
        brand: "Apple",
        price: 110000,
        image: "Photos/iPhone_13.jpg",
        rating: 4.7,
        specs: {
            screen: "6.1\" Super Retina",
            refresh: "60Hz",
            ram: "4GB",
            storage: "128GB",
            camera: "12MP Dual",
            battery: "3240mAh",
            processor: "A15 Bionic",
            network: "5G",
        },
    },
    {
        id: 39,
        name: "iPhone 14 Pro Max",
        brand: "Apple",
        price: 230000,
        image: "Photos/iPhone_14_Pro_Max.jpg",
        rating: 4.9,
        specs: {
            screen: "6.7\" Super Retina",
            refresh: "120Hz",
            ram: "6GB",
            storage: "256GB",
            camera: "48MP Triple",
            battery: "4323mAh",
            processor: "A16 Bionic",
            network: "5G",
        },
    },
    {
        id: 40,
        name: "iPhone 15",
        brand: "Apple",
        price: 175000,
        image: "Photos/iPhone_15.jpg",
        rating: 4.8,
        specs: {
            screen: "6.1\" Super Retina",
            refresh: "60Hz",
            ram: "6GB",
            storage: "128GB",
            camera: "48MP Dual",
            battery: "3349mAh",
            processor: "A16 Bionic",
            network: "5G",
        },
    },
    {
        id: 41,
        name: "Samsung Galaxy Z Flip 5",
        brand: "Samsung",
        price: 155000,
        image: "Photos/Samsung_Galaxy_Z_Flip_5.jpg",
        rating: 4.6,
        specs: {
            screen: "6.7\" Foldable AMOLED",
            refresh: "120Hz",
            ram: "8GB",
            storage: "512GB",
            camera: "12MP Dual",
            battery: "3700mAh",
            processor: "Snapdragon 8 Gen 2",
            network: "5G",
        },
    },
    {
        id: 42,
        name: "Xiaomi 14",
        brand: "Xiaomi",
        price: 160000,
        image: "Photos/Xiaomi_14.jpg",
        rating: 4.8,
        specs: {
            screen: "6.36\" LTPO OLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "50MP Leica",
            battery: "4610mAh",
            processor: "Snapdragon 8 Gen 3",
            network: "5G",
        },
    },
    {
        id: 43,
        name: "Honor Magic 6 Pro",
        brand: "Honor",
        price: 215000,
        image: "Photos/Honor_Magic_6_Pro.jpg",
        rating: 4.9,
        specs: {
            screen: "6.8\" LTPO OLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "180MP Periscope",
            battery: "5600mAh",
            processor: "Snapdragon 8 Gen 3",
            network: "5G",
        },
    },
    {
        id: 44,
        name: "Google Pixel 9",
        brand: "Google Pixel",
        price: 190000,
        image: "Photos/Google_Pixel_9.jpg",
        rating: 4.8,
        specs: {
            screen: "6.3\" OLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "256GB",
            camera: "50MP Dual",
            battery: "4700mAh",
            processor: "Tensor G4",
            network: "5G",
        },
    },
    {
        id: 45,
        name: "Samsung Galaxy S23 Ultra",
        brand: "Samsung",
        price: 195000,
        image: "Photos/Samsung_Galaxy_S23_Ultra.jpg",
        rating: 4.9,
        specs: {
            screen: "6.8\" Dynamic AMOLED",
            refresh: "120Hz",
            ram: "12GB",
            storage: "512GB",
            camera: "200MP Quad",
            battery: "5000mAh",
            processor: "Snapdragon 8 Gen 2",
            network: "5G",
        },
    }
];

const brands = ["Apple", "Samsung", "Xiaomi", "Oppo", "Vivo", "OnePlus", "Google Pixel", "Realme", "Nothing", "Honor", "Huawei", "Tecno", "Infinix"];
